### ISSUE TITLE
Prometheus warnings on startup

### ISSUE THREAD

**Issue by bassosimone** [m-lab/ndt-server#103]
```
2019/04/10 19:40:34 WARNING: Starting metrics server with ":9090" when flag is :9990
2019/04/10 19:40:34 WARNING: Update code to use `prometheusx.MustStartMetricsServer()`
```

Apparently, the flag is also not honoured. Reported by @mattmathis.

**Comment by pboothe** [comment]
This is because your code is using the deprecated `MustStartPrometheus` and a custom flag instead of the preferred `MustServeMetrics` and a standard flag.
