### ISSUE TITLE
NDT legacy sockets need a timeout set

### ISSUE THREAD

**Issue by pboothe** [m-lab/ndt-server#122]
If we are worried about "slow drip" clients (and I am a little worried, if I am being honest), then we should set a socket timeout of 5 minutes in the future on the control channel socket (and all other opened sockets) and then depend on that timeout. This allows us to ignore the "slow drip client" problem inside tests.

Something like: 
```c
setsockopt(ctrlsockfd, SOL_SOCKET, SO_RCVTIMEO, ...);
setsockopt(ctrlsockfd, SOL_SOCKET, SO_SNDTIMEO, ...);
```
but in Go. `set_socket_timeout_or_die` is what the original NDT server code does in https://github.com/m-lab/ndt/blob/master/src/network.c#L860

**Comment by bassosimone** [comment]
My experience with `ndt7` in Go lead me to the following hint, which may be useful also in this `ndt5` use case.(This is in turn inspired by a suggestion from @gfr10598, IIRC, when last year we were working on another ndt5 server.) Basically, set a deadline that expires when the specific subtest is over. (Optionally configure the socket to `RST` on close.) This is nice from many points of view, including that you really end the subtest when you're supposed to, and that you just arm once the timer pertaining to a socket, so you really minimise the number of things you do when you are measuring performance. Hope it helps.

**Comment by pboothe** [comment]
I think this is better solved by setting contexts that have deadlines. Go has its own deadline layer on top of setsockopt, and I can't seem to use it in a way that doesn't confound my expectations for how it should work.

**Comment by bassosimone** [comment]
> Go has its own deadline layer on top of setsockopt, and I can't seem to use it in a way that doesn't confound my expectations for how it should work.

Do you mean that Go calls select(2), hence SO_RCVTIMEO is not effective?

> I think this is better solved by setting contexts that have deadlines

Yes. My understanding is that it's like a `conn` has two internal contexts and `SetReadDeadline` and `SetWriteDeadline` allow to manipulate such contexts. Is there a better way to pass a context for cancellation directly to an I/O operation?

**Comment by pboothe** [comment]
What I have been doing is having a goroutine that calls `Close()` when the context is cancelled.  For example: https://github.com/m-lab/ndt-server/blob/master/ndt5/plain/plain.go#L91

**Comment by pboothe** [comment]
As far as what Go does: I don't know. I just know that when I use the API to try and do timeouts, I seem to always get deadlocks instead.
