### ISSUE TITLE
Make it easy for developers to pair client side and server side data.

### ISSUE THREAD

**Issue by mattmathis** [m-lab/ndt-server#123]
Expose the uuid to the client.  (both versions)

**Comment by bassosimone** [comment]
I'm wondering how we could expose the UUID in the legacy protocol. Maybe @pboothe has ideas?

**Comment by pboothe** [comment]
For the legacy protocol, my idea is: don't touch it, and migrate the client who wants this feature to NDT7.

Why do you need the UUID in the legacy client Matt?

**Comment by pboothe** [comment]
Fixed in #186

**Comment by bassosimone** [comment]
Then, can we close this?
