### ISSUE TITLE
Enable network layer debugging

### ISSUE THREAD

**Issue by mattmathis** [m-lab/ndt-server#124]
Expose to the client: the connection tuple as seen by the server.

This supports use cases such as: client side traceroute; mid path packet capture; manual NAT diagnosis, etc which require knowing the actual 4-tuple used on the wide area.

**Comment by bassosimone** [comment]
Is it possible to apply this concept also to ndt5, @pboothe? If not, then we can close this issue.

**Comment by stephen-soltesz** [comment]
I strongly suggest that we not add new features to the "legacy" protocol.

**Comment by bassosimone** [comment]
Then, we should probably close this issue, shan't we?
