### ISSUE TITLE
ndt7: client can overwrite socket_uuid

### ISSUE THREAD

**Issue by bassosimone** [m-lab/ndt-server#131]
Discovered with @stephen-soltesz when looking at data. The spec says that servers must not save any client metadata beginning with `server`. Either we change the spec to say that we will put client metadata in a sub-dictionary (my preference as is more robust _by definition_) or we rename `socket_uuid` to `server_socket_uuid`. @pboothe what do you think?

**Comment by pboothe** [comment]
server_socket_uuid sounds good to me.

**Comment by pboothe** [comment]
But, like you, I also prefer not mixing namespaces.

I think we should put client-generated metadata in a separate section from server-generated metadata.  They are not the same, and they should receive different levels of scrutiny and/or trust.

**Comment by bassosimone** [comment]
This is not a problem anymore after #149
