### ISSUE TITLE
Error with tls certificate

### ISSUE THREAD

**Issue by gnomikos** [m-lab/ndt-server#136]
Hello,
running only the two docker commands as reported in readme I get the following errors, any feedback?

Many thanks

2019/06/19 10:45:20 argsfromenv.go:38: Argument cert=/certs/cert.pem
2019/06/19 10:45:20 argsfromenv.go:38: Argument datadir=/var/spool/ndt
2019/06/19 10:45:20 argsfromenv.go:38: Argument key=/certs/key.pem
2019/06/19 10:45:20 argsfromenv.go:38: Argument legacy.protocol.verbose=false
2019/06/19 10:45:20 argsfromenv.go:38: Argument legacy_addr=:3001
2019/06/19 10:45:20 argsfromenv.go:38: Argument legacy_ws_addr=127.0.0.1:3002
2019/06/19 10:45:20 argsfromenv.go:38: Argument legacy_wss_addr=:3010
2019/06/19 10:45:20 argsfromenv.go:38: Argument ndt7_addr=:443
2019/06/19 10:45:20 argsfromenv.go:38: Argument prometheusx.listen-address=:9990
2019/06/19 10:45:20 argsfromenv.go:38: Argument uuid-prefix-file=george_1554293143_unsafe
2019/06/19 10:45:20 ndt-server.go:129: About to listen for unencrypted legacy NDT tests on 127.0.0.1:3002
2019/06/19 10:45:20 ndt-server.go:144: About to listen for legacy WsS tests on :3010
2019/06/19 10:45:20 ndt-server.go:166: About to listen for ndt7 tests on :443
2019/06/19 10:45:26 h2_bundle.go:4177: http2: server: error reading preface from client 127.0.0.1:48132: remote error: tls: bad certificate
2019/06/19 10:45:26 h2_bundle.go:4177: http2: server: error reading preface from client 127.0.0.1:48134: remote error: tls: bad certificate
127.0.0.1 - - [19/Jun/2019:10:45:34 +0000] "GET /static/widget.html HTTP/2.0" 200 4796
127.0.0.1 - - [19/Jun/2019:10:45:34 +0000] "GET /static/jquery-1.12.1.min.js HTTP/2.0" 200 97403
127.0.0.1 - - [19/Jun/2019:10:45:34 +0000] "GET /static/gauge.min.js HTTP/2.0" 200 15944
127.0.0.1 - - [19/Jun/2019:10:45:34 +0000] "GET /static/script.js HTTP/2.0" 200 15384
127.0.0.1 - - [19/Jun/2019:10:45:34 +0000] "GET /static/ndt-browser-client.js HTTP/2.0" 200 21770
127.0.0.1 - - [19/Jun/2019:10:45:34 +0000] "GET /static/ndt-wrapper.js HTTP/2.0" 200 5917
127.0.0.1 - - [19/Jun/2019:10:45:34 +0000] "GET /static/style.css HTTP/2.0" 200 5490
127.0.0.1 - - [19/Jun/2019:10:45:34 +0000] "GET /static/fonts/digital-7-mono.ttf HTTP/2.0" 200 33992
127.0.0.1 - - [19/Jun/2019:10:45:34 +0000] "GET /static/fonts/League_Gothic.otf HTTP/2.0" 200 17332
127.0.0.1 - - [19/Jun/2019:10:45:34 +0000] "GET /favicon.ico HTTP/2.0" 200 307
2019/06/19 10:45:36 legacy.go:140: Handling connection 127.0.0.1:3010<=WS(S),JSON=>127.0.0.1:48138
2019/06/19 10:45:36 h2_bundle.go:4177: http2: server: error reading preface from client 127.0.0.1:33760: remote error: tls: bad certificate
2019/06/19 10:46:06 c2s.go:66: Could not successfully ServeOnce No connection created
2019/06/19 10:46:06 legacy.go:216: C2S - Could not run c2s test (error: No connection created)
2019/06/19 10:46:06 legacy.go:86: Wrote /var/spool/ndt/legacy/2019/06/19/george_1554293143_unsafe_0000000000000007.json
2019/06/19 10:46:06 legacy.go:126: Test failed, but we recovered: C2S - Could not run c2s test (error: No connection created)
2019/06/19 10:46:06 close.go:31: Could not close connection (tls: use of closed connection)
127.0.0.1 - - [19/Jun/2019:10:45:36 +0000] "GET /ndt_protocol HTTP/1.1" 200 0

**Comment by pboothe** [comment]
Do those certificate & key files (/certs/cert.pem /certs/key.pem) work for other applications?

**Comment by gnomikos** [comment]
I dont think so.  How can I clean everything concerning certificates and initiate the tool again?

**Comment by pboothe** [comment]
You have to provide the TLS certs. They are your certs. They certify that your site is your site.  We can't provide them, as we are not a certificate provider. I recommend using LetsEncrypt if you need a certificate from a certificate provider.

The command specified in the readme expects you to have a file named `key.pem` and a file named `cert.pem` located in the current working directory. We can't make those files for you, you have to get those files from a certificate provider.

**Comment by bassosimone** [comment]
@gnomikos do you need further assistance here?

**Comment by bassosimone** [comment]
I believe we can close the issue for now. Please @gnomikos, reopen if you need further assistance!
