### ISSUE TITLE
Maybe a bad idea for ndt7 to depend on web100.

### ISSUE THREAD

**Issue by gfr10598** [m-lab/ndt-server#147]
This repo builds the web100 libraries and old NDT client.  Having this dependency seems like a problem in the long term.

**Comment by bassosimone** [comment]
I am confused. I think you can build all the `ndt7` code without a real dependency on `web100` since AFAIK that code does not ever import `web100`. Am I missing something?

**Comment by pboothe** [comment]
This is WAI.
