### ISSUE TITLE
Remove ConnectionInfo from model.Measurement

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/ndt-server#150]
Today the ConnectionInfo is sent to clients at most once by the ndt-server as part of a model.Measurement struct. This usage overloads the model.Measurement struct and complicate reasoning about and using the value of these fields for archival schemas. Two separate structs (one for ConnectionInfo one for Measurement) sent at two distinct times would simplify.

**Comment by bassosimone** [comment]
It seems the problem you want to solve is "simplify reasoning about and using the value of the fields for archival schemas". I wonder whether the solution is just to flag `*ConnectionInfo` such that it is not saved inside of BigQuery. I believe `bigquery:"-"` does that. Would that be enough?

**Comment by stephen-soltesz** [comment]
Okay.
