### ISSUE TITLE
ndt7/spec: use same variables as in kernel

### ISSUE THREAD

**Issue by bassosimone** [m-lab/ndt-server#157]
We should use exactly the same variable names and measurements units as the Linux kernel and, additionally, we should specify the unit in the variable name. This will reduce all possible levels of ambiguity, especially in BigQuery queries. Discussed with @pboothe.

**Comment by pboothe** [comment]
I think the right thing is to use the `tcp.LinuxTCPInfo` struct from https://github.com/m-lab/tcp-info/blob/master/tcp/tcpinfo.go#L57

**Comment by bassosimone** [comment]
@pboothe okay, I believe that's an excellent choice to reduce code duplication and, moreover, I am super happy that all the TCPInfo fields have been mapped there.

**Comment by pboothe** [comment]
the `ndt-server/tcpinfox` package may have everything you need to get this done.

**Comment by bassosimone** [comment]
Done in #180
