### ISSUE TITLE
ndt5: server should close download connection after 10sec

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/ndt-server#160]
The legacy server used to close the download test connection immediately after it was done sending.

Large client populations are reported failures due to timeout because the new ndt-server waits to close the test connection until sending the TestFinalize message on the control connection.

For single-threaded clients, it is simpler to block on the test connection and then continue reading on the control connection.

**Comment by stephen-soltesz** [comment]
Blocking https://github.com/m-lab/dev-tracker/issues/401

**Comment by stephen-soltesz** [comment]
Resolved by https://github.com/m-lab/k8s-support/releases/tag/v1.2.5

**Comment by bassosimone** [comment]
As reported in https://github.com/ooni/probe/issues/877#issuecomment-552773939, we noticed that the issue has resurfaced for OONI, so I'm opening this issue again.

With @robertodauria today we tested a fix that, deployed on sandbox, seems to fix OONI and all other clients that assume that the server closes the connection.

**Comment by stephen-soltesz** [comment]
Thanks to @robertodauria & @bassosimone we tracked this down to an apparent accidental regression in closing all fds while collecting performance stats in https://github.com/m-lab/ndt-server/pull/179 -- @robertodauria has a fix in progress.

**Comment by mehtab11** [comment]
@robertodauria - to confirm and then close.
