### ISSUE TITLE
ndt5: frequent ERROR_DISCOVERING_UUID files for valid tests

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/ndt-server#178]
While investigating the recent ndt-server deployment, I found that a significant number of result files included the "ERROR_DISCOVERING_UUID" filename interleaved with other file times. The pod had 0 restarts -- so this is occurring at "steady state" for the server.

A random sample showing interleaved files:

```
-rw-r--r--    1 root     root           649 Aug 27 15:19 ndt-tkqtg_1566056235_0000000000004317.json
-rw-r--r--    1 root     root           601 Aug 27 15:19 ndt-tkqtg_1566056235_0000000000004314.json
-rw-------    1 root     root           637 Aug 27 15:19 ERROR_DISCOVERING_UUID226390493.json
-rw-r--r--    1 root     root           651 Aug 27 15:19 ndt-tkqtg_1566056235_000000000000430E.json
-rw-r--r--    1 root     root           602 Aug 27 15:19 ndt-tkqtg_1566056235_000000000000430A.json
--
-rw-r--r--    1 root     root          1186 Aug 27 15:18 ndt-tkqtg_1566056235_00000000000042F4.json
-rw-r--r--    1 root     root           328 Aug 27 15:17 ndt-tkqtg_1566056235_00000000000042F9.json
-rw-------    1 root     root           645 Aug 27 15:17 ERROR_DISCOVERING_UUID886927094.json
-rw-r--r--    1 root     root           603 Aug 27 15:17 ndt-tkqtg_1566056235_00000000000042EC.json
-rw-r--r--    1 root     root           663 Aug 27 15:17 ndt-tkqtg_1566056235_00000000000042E7.json
```

From BQ this appears to happen ~6000 - 8000 times / day across the fleet.

```
SELECT TIMESTAMP_TRUNC(result.StartTime, DAY) as day, COUNT(*)
FROM `mlab-oti.base_tables.ndt5`  
WHERE test_id LIKE '%ERROR%'
GROUP BY day
ORDER BY day
```

These files appear to contain valid C2S & S2C rates.

**Comment by stephen-soltesz** [comment]
This came up again yesterday with @gfr10598 looking into tcpinfo.

Error frequency:

* ndt5 ~0.5%
  - S2C ~7k-8k for ~1.7M tests / day.
  - C2S ~3k-4k for ~1.5M tests / day.
* tcpinfo - 0%
  - No UUIDs with the error string (not all tcpinfo data was available, but a random sample).

When we look at how the two services generate the UUID:

* tcpinfo only uses [`uuid.FromCookie`][tu] -- makes sense that no error is possible here.
* ndt-server has two paths:
  - [`uuid.FromTCPConn`][fc] in netConnection. 
  - [`uuid.FromFile`][fd] in fdcache (used by the wsConnection).

When breaking the error down by protocol, only WS & WSS clients see the uuid error (wsConnection).

**This implies that there is a problem with uuid.FromFile or the fdcache.**

The rate may be low enough that this is not a priority to fix. But, this info could help focus the debugging.

[fd]: https://github.com/m-lab/ndt-server/blob/850f9f720681dfb6b5f9f90c053f87880116fc40/fdcache/fdcache.go#L176
[fc]: https://github.com/m-lab/ndt-server/blob/850f9f720681dfb6b5f9f90c053f87880116fc40/ndt5/protocol/protocol.go#L298
[tu]: https://github.com/m-lab/tcp-info/search?q=uuid.FromCookie&unscoped_q=uuid.FromCookie

**Comment by pboothe** [comment]
I suspect the fdcache. uuid.FromFile is pretty straighforward, but the fdcache is an attempt to eliminate a library abstraction, and there are many ways those can go wrong.

**Comment by stephen-soltesz** [comment]
After deploying the netx.Listener that removes the fdcache, (https://github.com/m-lab/ndt-server/pull/297), the ERROR_DISCOVERING_UUID files have dropped to zero shortly after deployment.

<img width="670" alt="Screen Shot 2020-06-23 at 10 42 28 AM" src="https://user-images.githubusercontent.com/1085316/85418114-65dfff80-b53e-11ea-8365-430fda965766.png">
