### ISSUE TITLE
Remove cmd/ndt-client

### ISSUE THREAD

**Issue by bassosimone** [m-lab/ndt-server#190]
We have determined with @pboothe that we will keep the Go client outside of this codebase and we will keep the JavaScript client in this codebase. We already have an official client outside of this codebase. Let's therefore zap the other client we have in this codebase.

**Comment by pboothe** [comment]
As we do so, let's make sure that we migrate the unit tests over as well.

**Comment by pboothe** [comment]
Done in #203
