### ISSUE TITLE
ndt7/spec: consider making every measurement actionable

### ISSUE THREAD

**Issue by bassosimone** [m-lab/ndt-server#194]
The current measurement message omits the five tuple, and the UUID, after the first measurement message. Also, we do not include any summary fields. It may help client implementors to always include the five tuple, and UUID, and perhaps to compute some easy summary fields (like the max-max-bandwidth and the min-min-RTT). This way, the last message you see is always reasonable and meaningful and you don't need to inspect all of them unless you need that. (The amount of bandwidth wasted is basically zero, because we also measure the measurement messages.)

**Comment by critzo** [comment]
Thank you @bassosimone and @pboothe for this issue. From an end-user perspective, a summary message is a requirement IMHO. NDT currently provides a summary and the new version should as well. The summary message will also be needed in the speed.measurementlab.net client as well as other third party integrations.

**Comment by pboothe** [comment]
I think that the approach of making every message a summary message is a good one. That way, there isn't a "we're done here" ceremony, which is a brittle thing because it depends on clients sticking around and doing stuff after they've potentially already gotten what they want.

**Comment by critzo** [comment]
Cool. Makes sense. If there's a "we're done here" in my mind, it's that the clients we build and support demonstrate a best practice of using the summary data. If we demonstrate it using our own reference clients, other third party clients will be more likely to follow our lead.

**Comment by bassosimone** [comment]
@critzo consider the current web client at speed.measurementlab.net. My understanding is that it shows "ping", download speed and upload speed. If my understanding is correct, then you can already obtain the same kind of information from ndt7 by doing the following:

* take the last message with `"Origin": "client"` and `"Test": "download"` and divide `"AppInfo.NumBytes"` by `"AppInfo.ElapsedTime"`: this is the average download speed in bytes per microsecond and you can easily convert to bits per second

*  take the last message with `"Origin": "client"` and `"Test": "upload"` and divide `"AppInfo.NumBytes"` by `"AppInfo.ElapsedTime"`: this is the average upload speed in bytes per microsecond and you can easily convert to bits per second

* take the last message with `"Origin": "server"` and `"Test": "download"` and use the `"TCPInfo.MinRTT"` to compute the "ping": you just need to convert from microsecond to second

The recommended way of doing that is to have variables in the code that invokes the client and compute the metrics you need for every message you receive. At the end of the test you have the metrics you need. Does this make sense? Are you advocating for adding this code to the reference client?

**Comment by pboothe** [comment]
To be done:
* Send connection metadata with every message
* Ensure every message is also a meaningful summary message

**Comment by bassosimone** [comment]
cc: @robertodauria

**Comment by bassosimone** [comment]
I have taken care of everything that needs to be done: https://github.com/m-lab/ndt-server/issues/194#issuecomment-539100964
