### ISSUE TITLE
Refactor ndt7/client.go as an explicit regress test

### ISSUE THREAD

**Issue by bassosimone** [m-lab/ndt-server#22]

**Comment by bassosimone** [comment]
@pboothe we have now an external reference client at https://github.com/m-lab/ndt7-client-go that should probably be used instead of the bundled client. The only missing bit to have ndt7-client-go replace the bundled client is https://github.com/m-lab/ndt7-client-go/issues/15.

On a related note, do we want to keep distributing an embedded JavaScript client with the server?

**Comment by bassosimone** [comment]
@pboothe I do see _some_ value in having very small clients in this repo. Do you agree?

**Comment by pboothe** [comment]
I see negative value. If the clients are in this repo, then they are the canonical clients.

**Comment by bassosimone** [comment]
We determined in a conversation with @pboothe that we'll remove the Go client that is in tree and use the one at github.com/m-lab/ndt7-client-go. So this issue is now obsoleted by #190.
