### ISSUE TITLE
Failure to build under docker

### ISSUE THREAD

**Issue by viper93458** [m-lab/ndt-server#220]
When using the docker image, it seems to fail at step 5/9. Thoughts?

Step 5/9 : RUN /go/src/github.com/m-lab/ndt-server/build.sh
 ---> Running in 3b349c1d1c0a
+ topdir
+ dirname /go/src/github.com/m-lab/ndt-server/build.sh
+ cd /go/src/github.com/m-lab/ndt-server
+ pwd -P
+ cd /go/src/github.com/m-lab/ndt-server
+ git describe --tags
fatal: not a git repository (or any of the parent directories): .git
+ VERSION=
ERROR: Service 'ndt-server' failed to build: The command '/bin/sh -c /go/src/github.com/m-lab/ndt-server/build.sh' returned a non-zero code: 128

-William

**Comment by pboothe** [comment]
How did you get the source code?  Did you do "git clone" or did you do some other thing?

**Comment by viper93458** [comment]
Hello and thank you kindly for the reply. I created the ndt-server directory under my home directory and then cloned the GIT repository by using wget to pull the zip. I unzipped it in my ndt-server directory and followed the instructions on GitHub to run the manual docker build. I also attempted using docker compose with the same issue.

I have repulled the latest docker image as well with the failure in the same place. This is all under the latest Alpine Linux build.

-William

**Comment by pboothe** [comment]
The build process assumes you used either "go get github.com/ndt-server" or "git clone git@github.com:m-lab/ndt-server.git" or "git clone https://github.com/m-lab/ndt-server.git".  Without doing one of those things, there is no way for us to determine the git commit hash, which means that the part of building the docker image where we record that hash in the binary will fail.

**Comment by viper93458** [comment]
Ok I'll give that a shot! Thanks. Still new to docker. ;)

I'll report back once I try.

-William

**Comment by viper93458** [comment]
That did indeed get me past the issue. Thank you kindly for the help!

XXXXX:~# git clone https://github.com/m-lab/ndt-server.git
Cloning into 'ndt-server'...
remote: Enumerating objects: 40, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 2459 (delta 16), reused 19 (delta 9), pack-reused 2419
Receiving objects: 100% (2459/2459), 633.43 KiB | 2.38 MiB/s, done.
Resolving deltas: 100% (1356/1356), done.
XXXXX:~# cd ndt-server/
XXXXX:~/ndt-server# ls
AUTHORS                    html
Dockerfile                 lame_duck.prom
Dockerfile.local           logging
LICENSE                    metadata
README.md                  metrics
TestDockerfile             ndt-server.go
bbr                        ndt-server_test.go
build.sh                   ndt5
cloud-config.yaml          ndt7
collectd.prom              platformx
data                       spec
deploy_ndt_to_gce.sh       tcpinfox
docker-compose.yml         test.sh
fdcache                    testdata
fullstack                  version
gen_local_test_certs.bash
XXXXX:~/ndt-server# docker build . -t ndt-server
Sending build context to Docker daemon  1.401MB
Step 1/9 : FROM golang:alpine as ndt-server-build
 ---> 3024b4e742b0
Step 2/9 : RUN apk add --no-cache git gcc linux-headers musl-dev
 ---> Using cache
 ---> d8e100f7d423
Step 3/9 : ADD . /go/src/github.com/m-lab/ndt-server
 ---> 9d91a9ada566
Step 4/9 : RUN /go/src/github.com/m-lab/ndt-server/build.sh
 ---> Running in a4defbd43ba1
+ topdir
+ dirname /go/src/github.com/m-lab/ndt-server/build.sh
+ cd /go/src/github.com/m-lab/ndt-server
+ pwd -P
+ cd /go/src/github.com/m-lab/ndt-server
+ git describe --tags
+ VERSION=v0.13.4
+ versionflags='-X github.com/m-lab/ndt-server/version.Version=v0.13.4'
+ git log -1 '--format=%h'
+ COMMIT=69b42dd
+ versionflags='-X github.com/m-lab/ndt-server/version.Version=v0.13.4 -X github.com/m-lab/go/prometheusx.GitShortCommit=69b42dd'
+ go get -v -t -tags netgo -ldflags '-X github.com/m-lab/ndt-server/version.Version=v0.13.4 -X github.com/m-lab/go/prometheusx.GitShortCommit=69b42dd -extldflags "-static"' .
github.com/m-lab/go (download)
github.com/prometheus/client_golang (download)
github.com/beorn7/perks (download)
github.com/cespare/xxhash (download)
github.com/golang/protobuf (download)
github.com/prometheus/client_model (download)
github.com/prometheus/common (download)
github.com/matttproud/golang_protobuf_extensions (download)
github.com/prometheus/procfs (download)
github.com/apex/log (download)
github.com/pkg/errors (download)
github.com/gorilla/handlers (download)
github.com/gorilla/websocket (download)
github.com/google/uuid (download)
github.com/m-lab/uuid (download)
github.com/m-lab/tcp-info (download)
github.com/prometheus/prometheus (download)
get "gopkg.in/m-lab/pipe.v3": found meta tag get.metaImport{Prefix:"gopkg.in/m-lab/pipe.v3", VCS:"git", RepoRoot:"https://gopkg.in/m-lab/pipe.v3"} at //gopkg.in/m-lab/pipe.v3?go-get=1
gopkg.in/m-lab/pipe.v3 (download)
github.com/m-lab/go/flagx
net
crypto/x509
crypto/tls
net/textproto
vendor/golang.org/x/net/http/httpguts
vendor/golang.org/x/net/http/httpproxy
net/http/httptrace
net/http
github.com/m-lab/go/httpx
github.com/m-lab/go/rtx
github.com/beorn7/perks/quantile
github.com/cespare/xxhash
github.com/golang/protobuf/proto
github.com/prometheus/client_model/go
github.com/prometheus/client_golang/prometheus/internal
github.com/matttproud/golang_protobuf_extensions/pbutil
github.com/prometheus/common/internal/bitbucket.org/ww/goautoneg
github.com/prometheus/common/model
github.com/prometheus/common/expfmt
github.com/prometheus/procfs/internal/fs
github.com/prometheus/procfs/internal/util
github.com/prometheus/procfs
github.com/prometheus/client_golang/prometheus
github.com/prometheus/client_golang/prometheus/promauto
github.com/prometheus/client_golang/prometheus/promhttp
github.com/m-lab/go/prometheusx
github.com/pkg/errors
github.com/apex/log
github.com/apex/log/handlers/json
github.com/gorilla/handlers
github.com/m-lab/ndt-server/logging
github.com/m-lab/go/warnonerror
github.com/m-lab/ndt-server/ndt5/metrics
github.com/gorilla/websocket
github.com/google/uuid
github.com/m-lab/uuid/prefix
github.com/m-lab/uuid/socookie
github.com/m-lab/uuid
github.com/m-lab/ndt-server/fdcache
github.com/m-lab/tcp-info/tcp
github.com/m-lab/ndt-server/tcpinfox
github.com/m-lab/ndt-server/ndt5/web100
github.com/m-lab/ndt-server/ndt5/protocol
github.com/m-lab/ndt-server/ndt5/ndt
github.com/m-lab/ndt-server/ndt5/c2s
github.com/m-lab/ndt-server/metadata
github.com/m-lab/ndt-server/ndt5/control
github.com/m-lab/ndt-server/ndt5/s2c
github.com/m-lab/ndt-server/ndt7/model
github.com/m-lab/ndt-server/data
github.com/m-lab/ndt-server/metrics
github.com/m-lab/ndt-server/ndt5/meta
github.com/m-lab/ndt-server/version
github.com/m-lab/ndt-server/ndt5
github.com/m-lab/ndt-server/ndt5/tcplistener
github.com/m-lab/ndt-server/ndt5/ws
github.com/m-lab/ndt-server/ndt7/listener
github.com/m-lab/ndt-server/ndt5/singleserving
github.com/m-lab/ndt-server/ndt5/handler
github.com/m-lab/ndt-server/ndt5/plain
github.com/m-lab/ndt-server/ndt7/closer
github.com/m-lab/ndt-server/ndt7/ping
github.com/m-lab/ndt-server/ndt7/spec
github.com/m-lab/ndt-server/ndt7/download/sender
github.com/m-lab/go/memoryless
github.com/m-lab/ndt-server/bbr
github.com/m-lab/ndt-server/ndt7/measurer
github.com/m-lab/ndt-server/ndt7/receiver
github.com/m-lab/ndt-server/ndt7/results
github.com/m-lab/ndt-server/ndt7/saver
github.com/m-lab/ndt-server/ndt7/download
github.com/m-lab/ndt-server/ndt7/upload/sender
github.com/m-lab/ndt-server/ndt7/upload
github.com/m-lab/ndt-server/ndt7/handler
github.com/m-lab/ndt-server/platformx
github.com/m-lab/ndt-server
Removing intermediate container a4defbd43ba1
 ---> dd037d63bac5
Step 5/9 : FROM alpine
latest: Pulling from library/alpine
89d9c30c1d48: Already exists
Digest: sha256:c19173c5ada610a5989151111163d28a67368362762534d8a8121ce95cf2bd5a
Status: Downloaded newer image for alpine:latest
 ---> 965ea09ff2eb
Step 6/9 : COPY --from=ndt-server-build /go/bin/ndt-server /
 ---> 2521e14e3bc7
Step 7/9 : ADD ./html /html
 ---> 6382de79b327
Step 8/9 : WORKDIR /
 ---> Running in 52d0b9b3ab70
Removing intermediate container 52d0b9b3ab70
 ---> b76dcc7432de
Step 9/9 : ENTRYPOINT ["/ndt-server"]
 ---> Running in d80ce517706f
Removing intermediate container d80ce517706f
 ---> d731debd1318
Successfully built d731debd1318
Successfully tagged ndt-server:latest


-William

**Comment by pboothe** [comment]
Hooray! Good luck in using NDT-server! (I wrote large chunks of it, so I am always happy to hear about it being useful to people)

**Comment by viper93458** [comment]
Seems to be running however the widget doesn't work. It errors out. :(

I can hit https://<server ip>/static/ndt7.html and immediately start getting upload and download results, but when going to /static/widget.html it gives the gauges, but the test won't run.  Going to /metrics returns page not found. The port numbers that are provided when you browse the root site https://<server IP> don't seem to be applicable to the docker version.


This is an NDT server.

You can run an NDT7 test (recommended) by going here:
   :4443/static/ndt7.html

You can run an NDT5 test here:
   :3001/static/widget.html (over http and websockets)
   :3010/static/widget.html (over https and secure websockets)
or just by pointing an older NDT client at the addresses and ports serving those URLs.

NDT7 is recommended for all new clients. NDT5 is for existing clients
(including all versions before 5) that have not yet been ported to NDT7. The
version "NDT6" was skipped entirely. (IPv6 has been supported by NDT for many
years, and the name NDT6 risked confusion with the naming scheme used by
ping6 and the like).

You can monitor its status on port :9090/metrics.

**Comment by pboothe** [comment]
try 
http://YOURSERVER:3001/static/widget.html
and
https://YOURSERVER:3010/static/widget.html
and
http://YOURSERVER:9090/metrics

The port number is important.

**Comment by viper93458** [comment]
Right, but the ports aren't exposed in the provided docker YML. I will add them now and test. :)

**Comment by pboothe** [comment]
The metrics will work, but the 3001 and 3010 tests will not.  If you really want to use NDT5 tests, then you have to pass in `docker run --net=host ndt-server`

**Comment by viper93458** [comment]
I don't need the NDT5 tests for any particular reason so I won't worry about those ports. The metrics don't seem to work even after exposing port 9090 in the docker-compose.yml and stopping/starting the container.

MYSERVER:~/ndt-server# cat docker-compose.yml
version: '3.7'
services:
  ndt-server:
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - ./certs:/certs
      - ./datadir:/datadir
      - ./html:/html
    cap_drop:
      - ALL
    ports:
      - "443:4443"
      - "9090:9090"
    command: [
      "./ndt-server",
      "-cert", "/certs/cert.pem",
      "-key", "/certs/key.pem",
      "-datadir", "/datadir",
      "-ndt7_addr", ":4443"
    ]

**Comment by pboothe** [comment]
Try :9990 instead. I suspect those docs are out of date. You can also look at the logs of the running server, which should say the port number when it starts up.

**Comment by viper93458** [comment]
I exposed 9990 and get a 404 page not found back from the webserver. I'll have a closer look at the logs by trying to access the running container's shell to see what I can see. Which log would be the one I am after?

**Comment by pboothe** [comment]
I was too brief. I meant: http://YOURSERVER:9990/metrics

The logs of interest are the ones that you can get by typing `docker logs d60420ea7ac3`, where that random binary string is acquired from `docker ps`

**Comment by viper93458** [comment]
I understood the proper URL. :)

I exposed 9990 and then tried the URL but it didn't work. I suspect I tried to quickly because it does work now! Thanks for helping out!
