### ISSUE TITLE
Exceptionally large tar file

### ISSUE THREAD

**Issue by gfr10598** [m-lab/ndt-server#226]
Not sure if this is a pusher problem or an ndt problem.
2019/12/19 19:41:39 task.go:138: Processed 268632 files, 0 nil data, 268632 rows committed, 0 failed, from gs://archive-mlab-sandbox/ndt/ndt5/2019/12/13/20191216T191101.404541Z-ndt5-mlab3-lga0t-ndt.tgz into ndt5_20191216

The archive is 27 MBytes, which is very reasonable

 27859806  2019-12-17T02:10:29Z  gs://archive-mlab-sandbox/ndt/ndt5/2019/12/13/20191216T191101.404541Z-ndt5-mlab3-lga0t-ndt.tgz

**Comment by gfr10598** [comment]
Looks like the size is not an issue.  However, it seems odd that a single machine would ever see this number of NDT tests, since we can't really handle more than a few hundred tests per minute, and pusher is supposed to push every two hours.  

Maybe this was a case where pusher was down? Should we add logic to split into 2 hours blocks if pusher gets behind?

**Comment by pboothe** [comment]
268632 files is a lot more files than we expect in an average tarfile.

**Comment by pboothe** [comment]
But this is probably our internal load testing?
