### ISSUE TITLE
NDT server should support admission controls based on current usage

### ISSUE THREAD

**Issue by pboothe** [m-lab/ndt-server#227]
The old server supported these, and we miss them.

**Comment by pboothe** [comment]
Related to #5

**Comment by stephen-soltesz** [comment]
See also https://github.com/m-lab/ndt-server/issues/221

**Comment by pboothe** [comment]
1. concurrent rate limiting ("no more than N clients at a time")
2. resource-based limiting
3. access-token based

**Comment by stephen-soltesz** [comment]
https://github.com/m-lab/dev-tracker/issues/542

**Comment by stephen-soltesz** [comment]
Access token work is part of :
* https://github.com/m-lab/dev-tracker/issues/573
* https://github.com/m-lab/dev-tracker/issues/574

**Comment by stephen-soltesz** [comment]
I'm going to mark this issue as obsolete or dup of other open issues and KRs.
