### ISSUE TITLE
Separate data.NDT5Result and data.NDT7Result structs

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/ndt-server#260]
This has several implications for m-lab/etl and m-lab/website.

In particular, the current code uses a shared/unified `data.NDTResult` struct. The etl/schema imports that struct directly and uses it to generate a schema.

Unfortunately, recent changes to the ndt7 data types have made the data.NDTResult struct incompatible with the current BQ schema.

To solve this, the proposal is to create two separate data.NDTResult structs (one for ndt5 & ndt7) with protocol-specific fields.

This should remain backward compatible with archived data for both tests (with the exception of the fields removed from ndt7). And, this will make the schemas generated for the respective datatypes type-specific (which is good) and the documentation for those tables include only relevant fields for that data type (also good).

Our thinking about how to create "unified tables" with this data has evolved to include "Standard Columns" and the Unified NDT history view. Going forward, we do not need for the output json to be common to the two datatypes in the ndt-server. Especially if this is holding back development velocity for the NDT7 protocol, and does not break ndt5 backward compatibility (it does not).

**Comment by yachang** [comment]
FYI, the removed field is result.Upload.ServerMeasurements.Elapsed, which block the ETL schema update code.

**Comment by stephen-soltesz** [comment]
Done!
