### ISSUE TITLE
ndt7/model.BBRInfo and tcp-info/inetdiag.BBRInfo are different & the same

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/ndt-server#272]
Both structs share a name but collect different information.

* https://github.com/m-lab/ndt-server/blob/master/bbr/bbr_linux.go#L23
* https://github.com/m-lab/tcp-info/blob/master/inetdiag/structs.go#L376

The inetdiag.BBRInfo struct faithfully replicates the linux tcp_bbr_info struct. The model.BBRInfo adds an ElapsedTime field and omits others.

What if we create a new summary struct that contains the faithful data?

Something like:

```golang
import "github.com/m-lab/tcp-info/inetdiag"

type BBRSummary struct{
    inetdiag.BBRInfo
    ElapsedTime int64
}
```

This would use the same approach as the model.TCPInfo struct (which references tcp-info types). https://github.com/m-lab/ndt-server/blob/master/ndt7/model/tcpinfo.go

```golang
import "github.com/m-lab/tcp-info/tcp"

// The TCPInfo struct contains information measured using TCP_INFO. This
// structure is described in the ndt7 specification.
type TCPInfo struct {
	tcp.LinuxTCPInfo
	ElapsedTime   int64
}
```

**Comment by pboothe** [comment]
Fixed and deployed
