### ISSUE TITLE
fullstack/Dockerfile build failing

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/ndt-server#287]
Dockerhub reported a failure in the fullstack configuration.

It appears that the install is expecting user-input, waits for 4 hours, and then is terminated by dockerhub build.

https://hub.docker.com/repository/registry-1.docker.io/measurementlab/ndt/builds/2ef9fd4d-87ac-4948-87ab-75c86024157e

Build duration: 240 min

```
Setting up tzdata (2019c-3ubuntu1) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
Configuring tzdata
------------------
Please select the geographic area in which you live. Subsequent configuration
questions will narrow this down by presenting a list of cities, representing
the time zones in which they are located.
1. Africa 4. Australia 7. Atlantic 10. Pacific 13. Etc
2. America 5. Arctic 8. Europe 11. SystemV
3. Antarctica 6. Asia 9. Indian 12. US
Geographic area:
Build canceled.
```

**Comment by stephen-soltesz** [comment]
FYI: @pboothe @yachang (could be related to recent traceroute-caller changes since it's the base image of the fullstack image.)

**Comment by stephen-soltesz** [comment]
This setting worked in epoxy-images for a non-interactive `debootstrap`:

```
export DEBIAN_FRONTEND=noninteractive
```

**Comment by stephen-soltesz** [comment]
@critzo reports that the most recent image does not wai (presumably the last one to build successfully).

**Comment by laiyi-ohlsen** [comment]
@critzo is a user reporting this? Can you say more about the use case?
