### ISSUE TITLE
Randomize payload when using cleartext WebSocket

### ISSUE THREAD

**Issue by bassosimone** [m-lab/ndt-server#332]
We should randomize the payload when using cleartext WebSocket. A bunch of zeroes is too easy to compress.

**Comment by nosnilmot** [comment]
I was about to have a go at implementing this, but it looks to me like it is already using random data [here](https://github.com/m-lab/ndt-server/blob/master/ndt7/download/sender/sender.go#L19), am I missing something?

**Comment by laiyi-ohlsen** [comment]
@bassosimone Do you have thoughts on the above? Is this already implemented?

**Comment by robertodauria** [comment]
As far as I can tell, this is implemented already.
