### ISSUE TITLE
NDT7 Migration

### ISSUE THREAD

**Issue by logmeinndt7** [m-lab/ndt-server#337]
I am trying to migrate to ndt7 from ndt5 and using  url :/v2/nearest/ndt/ndt7 for download and upload test.
then calling method "query_mlabns_curl" and getting response from ndt7 server is:
"results": [
    {
      "machine": "mlab3-maa02.mlab-oti.measurement-lab.org",
      "location": {
        "city": "Chennai",
        "country": "IN"
      },
      "urls": {
        "ws:///ndt/v7/download": "ws://ndt-mlab3-maa02.mlab-oti.measurement-lab.org/ndt/v7/download?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjMtbWFhMDIubWxhYi1vdGkubWVhc3VyZW1lbnQtbGFiLm9yZyJdLCJleHAiOjE2MjYxMTA5NjIsImlzcyI6ImxvY2F0ZSIsInN1YiI6Im5kdCJ9.gy-aJUS5Snnyw5OVd41tmVAGZaVyFtZZWmZVumhfUcT6Qjw_GV31Lf8oAyH087paTXGrTtHtlIUA0N2fwuFXDA",
        "ws:///ndt/v7/upload": "ws://ndt-mlab3-maa02.mlab-oti.measurement-lab.org/ndt/v7/upload?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjMtbWFhMDIubWxhYi1vdGkubWVhc3VyZW1lbnQtbGFiLm9yZyJdLCJleHAiOjE2MjYxMTA5NjIsImlzcyI6ImxvY2F0ZSIsInN1YiI6Im5kdCJ9.gy-aJUS5Snnyw5OVd41tmVAGZaVyFtZZWmZVumhfUcT6Qjw_GV31Lf8oAyH087paTXGrTtHtlIUA0N2fwuFXDA",
        "wss:///ndt/v7/download": "wss://ndt-mlab3-maa02.mlab-oti.measurement-lab.org/ndt/v7/download?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjMtbWFhMDIubWxhYi1vdGkubWVhc3VyZW1lbnQtbGFiLm9yZyJdLCJleHAiOjE2MjYxMTA5NjIsImlzcyI6ImxvY2F0ZSIsInN1YiI6Im5kdCJ9.gy-aJUS5Snnyw5OVd41tmVAGZaVyFtZZWmZVumhfUcT6Qjw_GV31Lf8oAyH087paTXGrTtHtlIUA0N2fwuFXDA",
        "wss:///ndt/v7/upload": "wss://ndt-mlab3-maa02.mlab-oti.measurement-lab.org/ndt/v7/upload?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjMtbWFhMDIubWxhYi1vdGkubWVhc3VyZW1lbnQtbGFiLm9yZyJdLCJleHAiOjE2MjYxMTA5NjIsImlzcyI6ImxvY2F0ZSIsInN1YiI6Im5kdCJ9.gy-aJUS5Snnyw5OVd41tmVAGZaVyFtZZWmZVumhfUcT6Qjw_GV31Lf8oAyH087paTXGrTtHtlIUA0N2fwuFXDA"
      }
    },
    {
      "machine": "mlab2-maa01.mlab-oti.measurement-lab.org",
      "location": {
        "city": "Chennai",
        "country": "IN"
      },
      "urls": {
        "ws:///ndt/v7/download": "ws://ndt-mlab2-maa01.mlab-oti.measurement-lab.org/ndt/v7/download?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjItbWFhMDEubWxhYi1vdGkubWVhc3VyZW1lbnQtbGFiLm9yZyJdLCJleHAiOjE2MjYxMTA5NjIsImlzcyI6ImxvY2F0ZSIsInN1YiI6Im5kdCJ9.BjdBXmtH4wRWqon6-bBYxrfQA--0zpivymX8OTs2XoJsQk4YM1D2lFGAWhVX6sIi9ySC8jbRExy55NJ19tc4BQ",
        "ws:///ndt/v7/upload": "ws://ndt-mlab2-maa01.mlab-oti.measurement-lab.org/ndt/v7/upload?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjItbWFhMDEubWxhYi1vdGkubWVhc3VyZW1lbnQtbGFiLm9yZyJdLCJleHAiOjE2MjYxMTA5NjIsImlzcyI6ImxvY2F0ZSIsInN1YiI6Im5kdCJ9.BjdBXmtH4wRWqon6-bBYxrfQA--0zpivymX8OTs2XoJsQk4YM1D2lFGAWhVX6sIi9ySC8jbRExy55NJ19tc4BQ",
        "wss:///ndt/v7/download": "wss://ndt-mlab2-maa01.mlab-oti.measurement-lab.org/ndt/v7/download?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjItbWFhMDEubWxhYi1vdGkubWVhc3VyZW1lbnQtbGFiLm9yZyJdLCJleHAiOjE2MjYxMTA5NjIsImlzcyI6ImxvY2F0ZSIsInN1YiI6Im5kdCJ9.BjdBXmtH4wRWqon6-bBYxrfQA--0zpivymX8OTs2XoJsQk4YM1D2lFGAWhVX6sIi9ySC8jbRExy55NJ19tc4BQ",
        "wss:///ndt/v7/upload": "wss://ndt-mlab2-maa01.mlab-oti.measurement-lab.org/ndt/v7/upload?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjItbWFhMDEubWxhYi1vdGkubWVhc3VyZW1lbnQtbGFiLm9yZyJdLCJleHAiOjE2MjYxMTA5NjIsImlzcyI6ImxvY2F0ZSIsInN1YiI6Im5kdCJ9.BjdBXmtH4wRWqon6-bBYxrfQA--0zpivymX8OTs2XoJsQk4YM1D2lFGAWhVX6sIi9ySC8jbRExy55NJ19tc4BQ"
      }
    },
    {
      "machine": "mlab3-bom01.mlab-oti.measurement-lab.org",
      "location": {
        "city": "Mumbai",
        "country": "IN"
      },
      "urls": {
        "ws:///ndt/v7/download": "ws://ndt-mlab3-bom01.mlab-oti.measurement-lab.org/ndt/v7/download?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjMtYm9tMDEubWxhYi1vdGkubWVhc3VyZW1lbnQtbGFiLm9yZyJdLCJleHAiOjE2MjYxMTA5NjIsImlzcyI6ImxvY2F0ZSIsInN1YiI6Im5kdCJ9.6vlN8hcEcIu8RIiTUAQeW8yL0FeYBlN8rthH3e40iT4JtIWhxJXuGOQevccOdjq1TPW8YWXzN50pEpR4LexzDA",
        "ws:///ndt/v7/upload": "ws://ndt-mlab3-bom01.mlab-oti.measurement-lab.org/ndt/v7/upload?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjMtYm9tMDEubWxhYi1vdGkubWVhc3VyZW1lbnQtbGFiLm9yZyJdLCJleHAiOjE2MjYxMTA5NjIsImlzcyI6ImxvY2F0ZSIsInN1YiI6Im5kdCJ9.6vlN8hcEcIu8RIiTUAQeW8yL0FeYBlN8rthH3e40iT4JtIWhxJXuGOQevccOdjq1TPW8YWXzN50pEpR4LexzDA",
        "wss:///ndt/v7/download": "wss://ndt-mlab3-bom01.mlab-oti.measurement-lab.org/ndt/v7/download?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjMtYm9tMDEubWxhYi1vdGkubWVhc3VyZW1lbnQtbGFiLm9yZyJdLCJleHAiOjE2MjYxMTA5NjIsImlzcyI6ImxvY2F0ZSIsInN1YiI6Im5kdCJ9.6vlN8hcEcIu8RIiTUAQeW8yL0FeYBlN8rthH3e40iT4JtIWhxJXuGOQevccOdjq1TPW8YWXzN50pEpR4LexzDA",
        "wss:///ndt/v7/upload": "wss://ndt-mlab3-bom01.mlab-oti.measurement-lab.org/ndt/v7/upload?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjMtYm9tMDEubWxhYi1vdGkubWVhc3VyZW1lbnQtbGFiLm9yZyJdLCJleHAiOjE2MjYxMTA5NjIsImlzcyI6ImxvY2F0ZSIsInN1YiI6Im5kdCJ9.6vlN8hcEcIu8RIiTUAQeW8yL0FeYBlN8rthH3e40iT4JtIWhxJXuGOQevccOdjq1TPW8YWXzN50pEpR4LexzDA"
      }
    },
    {
      "machine": "mlab2-bom02.mlab-oti.measurement-lab.org",
      "location": {
        "city": "Mumbai",
        "country": "IN"
      },
      "urls": {
        "ws:///ndt/v7/download": "ws://ndt-mlab2-bom02.mlab-oti.measurement-lab.org/ndt/v7/download?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjItYm9tMDIubWxhYi1vdGkubWVhc3VyZW1lbnQtbGFiLm9yZyJdLCJleHAiOjE2MjYxMTA5NjIsImlzcyI6ImxvY2F0ZSIsInN1YiI6Im5kdCJ9.hmXsyB0p9rNUkVkQhMJF2uJBOr5djtnim_fuKx39RJ5M0drLulhRx1wZSXoB9-g3i2r_6Xr2ul4MNm7Aa-n3BQ",
        "ws:///ndt/v7/upload": "ws://ndt-mlab2-bom02.mlab-oti.measurement-lab.org/ndt/v7/upload?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjItYm9tMDIubWxhYi1vdGkubWVhc3VyZW1lbnQtbGFiLm9yZyJdLCJleHAiOjE2MjYxMTA5NjIsImlzcyI6ImxvY2F0ZSIsInN1YiI6Im5kdCJ9.hmXsyB0p9rNUkVkQhMJF2uJBOr5djtnim_fuKx39RJ5M0drLulhRx1wZSXoB9-g3i2r_6Xr2ul4MNm7Aa-n3BQ",
        "wss:///ndt/v7/download": "wss://ndt-mlab2-bom02.mlab-oti.measurement-lab.org/ndt/v7/download?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjItYm9tMDIubWxhYi1vdGkubWVhc3VyZW1lbnQtbGFiLm9yZyJdLCJleHAiOjE2MjYxMTA5NjIsImlzcyI6ImxvY2F0ZSIsInN1YiI6Im5kdCJ9.hmXsyB0p9rNUkVkQhMJF2uJBOr5djtnim_fuKx39RJ5M0drLulhRx1wZSXoB9-g3i2r_6Xr2ul4MNm7Aa-n3BQ",
        "wss:///ndt/v7/upload": "wss://ndt-mlab2-bom02.mlab-oti.measurement-lab.org/ndt/v7/upload?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjItYm9tMDIubWxhYi1vdGkubWVhc3VyZW1lbnQtbGFiLm9yZyJdLCJleHAiOjE2MjYxMTA5NjIsImlzcyI6ImxvY2F0ZSIsInN1YiI6Im5kdCJ9.hmXsyB0p9rNUkVkQhMJF2uJBOr5djtnim_fuKx39RJ5M0drLulhRx1wZSXoB9-g3i2r_6Xr2ul4MNm7Aa-n3BQ"
      }
    }
  ]
}

After getting the above response, we are using the any one url from above urls as host name and trying to get the host details using GetAddrInfo() method
internal::Err Client::netx_resolve(const std::string &hostname,
			std::vector<std::string> *addrs) noexcept {
			assert(addrs != nullptr);
		
			addrinfo hints{};
			hints.ai_socktype = SOCK_STREAM;
			hints.ai_flags |= AI_NUMERICHOST | AI_NUMERICSERV;
			addrinfo *rp = nullptr;
			constexpr const char *portno = "80";  // any port would do
			int rv = sys->Getaddrinfo(hostname.data(), portno, &hints, &rp);
			if (rv != 0) {
				hints.ai_flags &= ~AI_NUMERICHOST;
				rv = sys->Getaddrinfo(hostname.data(), portno, &hints, &rp);
				if (rv != 0) {
					auto err = netx_map_eai(rv);
					LOG_WARN_F(TEXT(
						"netx_resolve: getaddrinfo() failed. libndt_errcode: %d (see enum Err)"), err);
					return err;
				}
				// FALLTHROUGH
			}

but we gett error code that host is not found "WSAHOST_NOT_FOUND
11001"

Please can anyone suggest, i am missing anything?

**Comment by robertodauria** [comment]
@logmeinndt7 what value are you passing to `Client::netx_resolve` exactly?

**Comment by logmeinndt7** [comment]
> @logmeinndt7 what value are you passing to `Client::netx_resolve` exactly?

**Comment by logmeinndt7** [comment]
> @logmeinndt7 what value are you passing to `Client::netx_resolve` exactly?

Hi thanks for quick reply, please see the values I am passing to

**Comment by logmeinndt7** [comment]
> @logmeinndt7 what value are you passing to `Client::netx_resolve` exactly?

Hi, Thanks for quick reply.
passing  value to Client::netx_resolve() is

ws:///ndt/v7/download": "ws://ndt-mlab3-maa02.mlab-oti.measurement-lab.org/ndt/v7/download?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjMtbWFhMDIubWxhYi1vdGkubWVhc3VyZW1lbnQtbGFiLm9yZyJdLCJleHAiOjE2MjYxMTA5NjIsImlzcyI6ImxvY2F0ZSIsInN1YiI6Im5kdCJ9.gy-aJUS5Snnyw5OVd41tmVAGZaVyFtZZWmZVumhfUcT6Qjw_GV31Lf8oAyH087paTXGrTtHtlIUA0N2fwuFXDA"

this is the host name which we receive from ndt7 server.

**Comment by robertodauria** [comment]
Hi @logmeinndt7 ,
That code seems to be based on [libndt](https://github.com/measurement-kit/libndt/blob/master/single_include/libndt.hpp#L25317), which has never been updated to support access tokens. It hasn't been maintained for quite some time now, and since then access tokens have become mandatory for the ndt7 protocol.

The Locate service (which is returning that JSON) now provides, in addition to the server's hostname, an access token that needs to be included in the request to the server. The code above likely still assumes Locate is sending the hostname only, and passes it to `Getaddrinfo` as-is. Since it's not just a hostname anymore, the DNS lookup fails.

A possible solution to that would be adding proper access token support, which probably involves splitting the URL returned by Locate into hostname + querystring and passing just the hostname part (up to `measurement-lab.org`) to `netx_resolve`, then making sure the access token (which is in the URL returned by Locate) is passed to the server when requesting a download/upload test.
