### ISSUE TITLE
ndt7: the server should give you the four tuple

### ISSUE THREAD

**Issue by bassosimone** [m-lab/ndt-server#61]
Suggested by @mattmathis. This probably means the server should tell the client what it thinks the client IP address is. This can be done with a specific protocol message.

**Comment by mattmathis** [comment]
Specifically the jason shown in the "advanced" tab for <server>:3010/static/widget.html should show the connection 4 tuple in parsible form.   It should also appear in the meta report used to generate the "details" tab.

**Comment by bassosimone** [comment]
@mattmathis how about:

```json
{
  "server": {
    "address": "1.2.3.4",
    "port": 1234
  },
  "client": {
    "address": "1.2.3.4",
    "port": 1234
  }
}
```

?

**Comment by pboothe** [comment]
Also, a UUID would be nice.

**Comment by bassosimone** [comment]
This has clearly been done in #126
