### ISSUE TITLE
Colons in filenames prevent using them on windows

### ISSUE THREAD

**Issue by bassosimone** [m-lab/ndt-server#64]
I've been inflicting myself pain for quite some time now, by also using a Windows development box, since we're working on OONI for Windows. A related side effect is that I am more likely to be hit by issues that I would not otherwise notice when working mainly on Unix. Here's one.

We write ndt7 file names as follows:

```go
name := dir + "/ndt7-" + timestamp.Format("2006-01-02T15:04:05.000000000Z") + "." + uuid + ".jsonl.gz"
```

This is not good for Windows, where file names cannot contain colons. This means that, if one downloads a tarball of ndt7 results and wants to open it from Windows, they cannot, unless they use the WOL environment (i.e. Unix). My suggestion would be to just drop the `-` and `:` between then various date components. After re-reading [the ISO8601 Wikipedia page](https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations), I am now convinced that it would be perfectly fine to use this format:

```go
name := dir + "/ndt7-" + timestamp.Format("20060102T150405.000000000Z") + "." + uuid + ".jsonl.gz"
```

Any objections, @pboothe? Otherwise, I can make a quick patch for this?

**Comment by pboothe** [comment]
Sounds good to me. I did not know about that limitation of windows file names: TIL!

**Comment by pboothe** [comment]
I will happily review a PR, but I do not want to be on the hook for doing this work.

**Comment by bassosimone** [comment]
> I will happily review a PR, but I do not want to be on the hook for doing this work

Sure, I assigned you to make sure you noticed this issue. I'll do that!
