### ISSUE TITLE
NDT should export its github commit

### ISSUE THREAD

**Issue by pboothe** [m-lab/ndt-server#93]
Using `go.prometheusx.GitShortCommit` as a link parameter.

**Comment by bassosimone** [comment]
If you build using `./build.sh`, the `version.Version` variable contains the output of `git describe --tags`, which is probably even more useful than the git commit alone, but also includes it.

**Comment by pboothe** [comment]
Yes!  The main thing here is that I want to 

1. use this capability in every repo and 
2. also export that information out via prometheus in a standard way.

Then we can build nice generic dashboards that tell us when our last update was and how long staging and production have been out of sync, and we can build alerts when they have been out of sync too long.  `version.Version` is great, but I think `prometheusx.GitDescribeLong` would be better. Then everything that uses prometheusx will have that metric available to be set at build time and exported at runtime.

I think you are right that the output of `git describe --tags` (or perhaps the output of `git describe --long` parsed into its three component parts `TAG-COMMITCOUNT-COMMITID`) would form an excellent basis for these metrics, dashboards, and alerts.

**Comment by pboothe** [comment]
Basically, I only want to have to do version parsing and exporting once, even though I care about this information in many repos.

**Comment by pboothe** [comment]
Work is being tracked in: https://github.com/m-lab/dev-tracker/issues/224 

Things are slightly complicated. A design doc is being produced.

**Comment by pboothe** [comment]
Closing this issue.  Follow the linked issue if you care.
